import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import AnimationWrapper from "@/components/client/AnimationWrapper";
import TransitionLayout from "@/components/TransitionLayout";

export const metadata: Metadata = {
  title: {
    template: "%s | AABEE, A Luxury Travel Agency | Forbes Select 200",
    default: "AABEE - A Luxury Travel Company | Forbes Select 200",
  },
  description: "Generated by create next app",
};

const inter = Inter({ weight: "300", subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TransitionLayout>
          <AnimationWrapper>
            <div className="flex min-h-screen flex-col">
              <NavBar></NavBar>
              {children}
              <Footer></Footer>
            </div>
          </AnimationWrapper>
        </TransitionLayout>
        <Analytics />
      </body>
    </html>
  );
}
